# docker-compose.yml

services:
  backend:
    build:
      context: ./backendMD
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./backendMD
      dockerfile: Dockerfile.celery
    command: celery -A celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./frontendMD
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia # Required to enable GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  redis_data:
  ollama:
