# backend/Dockerfile.celery

# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY ../requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Set environment variables for Celery
ENV OLLAMA_API_URL=$OLLAMA_API_URL
ENV OLLAMA_API_KEY=$OLLAMA_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV CELERY_BROKER_URL=$CELERY_BROKER_URL
ENV CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND

# Run the Celery worker
CMD ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info"]
